#Requires -Version 7
<#
.SYNOPSIS
    Fails if a tracked file, or a commit message in the range under review, credits an
    automated writing tool for work in this repository.

.DESCRIPTION
    This repository's policy is that commit messages, PR text, code comments and documentation
    never say a change was produced by an automated tool -- no co-authorship trailer for one, no
    "generated with" footer, no product name in a code comment. That has been enforced by hand
    since the fork started, and by hand is not a gate: one commit message on this branch's history
    already carried a stray tool-authorship phrase before a manual scan happened to catch it.

    Two independent checks, both driven by the same pattern table:

      1. Every tracked file (git grep -I, which already skips binary files -- see "Binary files"
         below), excluding external/ (Astrodienst's own vendored source, not this repository's
         writing) and this script's own path (which necessarily contains the literal pattern text
         it searches for -- a filter has to name what it filters).
      2. Every commit message in -CommitRange, if given. Skipped (not failed) when omitted, so
         this script still works as a plain content scan outside CI.

    Pattern design, and why each one is shaped the way it is:

      - Tool and vendor product names (case-sensitive, whole-word) -- "Claude", "Anthropic",
        "ChatGPT" -- chosen case-sensitive because these are proper nouns; a false positive would
        need an unrelated identifier that happens to capitalize the same way, which nothing in a
        Swiss Ephemeris port does.
      - "assistant", "copilot", "chatbot" (case-insensitive, whole-word) -- generic terms for a
        tool that writes text on someone's behalf. Whole-word matching keeps "assistant" from
        firing on a substring of some unrelated identifier; nothing in this codebase's domain
        (ephemeris calculation) uses any of these three words for anything else, verified with
        `git grep` against the tree this script was written against.
      - "Co-Authored-By" and "Claude-Session" (case-sensitive) -- the specific trailers automated
        commit tooling appends by default.
      - "Generated with" (case-sensitive, capital G) -- the standard footer phrase
        ("Generated with [...]"), not the bare word "generated", which is ordinary and legitimate
        throughout this repository's own documentation ("the baseline is generated from the
        port's own output", "t.exp was generated by setest", "regenerated with -ExpectedScope").
        Capitalization is the deliberate discriminator: every legitimate use found in this
        repository's own text is mid-sentence and lowercase ("was generated with setest"); the
        footer this pattern exists to catch is not. A leading word boundary also keeps
        "regenerated with" from matching "Generated with" as a substring regardless of case.

    Binary files: git grep -I applies the same "does this look like text" heuristic `git diff`
    uses to decide whether to print "Binary files ... differ", so a `.se1` ephemeris file (or any
    other binary asset) is never opened as text and can never produce a spurious match on a short
    pattern landing inside its byte stream.

    docs/upstream/ is untracked, so `git grep` (which searches the index, not the working tree)
    never sees it regardless of any explicit exclusion.

    False positives are the one thing that gets a check like this disabled, so every pattern above
    was checked against this repository's current tree before being added, and the phrasing was
    chosen specifically to avoid the near-misses found doing that (see "Generated with" above).
    Preferring a false negative to a false positive is not merely default caution here; it is
    calibrated against defects this exact scan produced during design and then was narrowed to
    avoid.

.PARAMETER RepoRoot
    Repository root. Defaults to the checkout containing this script.

.PARAMETER CommitRange
    A git revision range (e.g. "origin/release/2.10.03..HEAD") whose commit messages are also
    checked. Typically the range a pull request actually introduces -- see the CI workflow for how
    it is resolved. Omit to check tracked files only.
#>
[CmdletBinding()]
param(
    [string] $RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [string] $CommitRange
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false

Push-Location $RepoRoot
try {
    # This script's own path, relative to the repo root, in the form `git grep` reports it --
    # the one file allowed to contain the literal pattern text below.
    $selfPath = [System.IO.Path]::GetRelativePath($RepoRoot, $PSCommandPath).Replace('\', '/')

    # Each pattern paired with a human-readable label for the failure message. Patterns are .NET
    # regex; a leading "(?i)" makes that one pattern case-insensitive, its absence means
    # case-sensitive -- see the .DESCRIPTION for why each choice was made.
    $patterns = @(
        @{ Regex = '\bClaude\b'; Label = "product name 'Claude'" }
        @{ Regex = '\bAnthropic\b'; Label = "company name 'Anthropic'" }
        @{ Regex = '\bChatGPT\b'; Label = "product name 'ChatGPT'" }
        @{ Regex = '(?i)\bcopilot\b'; Label = "'copilot'" }
        @{ Regex = '(?i)\bchatbot\b'; Label = "'chatbot'" }
        @{ Regex = '(?i)\bassistant\b'; Label = "'assistant'" }
        @{ Regex = 'Co-Authored-By'; Label = "'Co-Authored-By' trailer" }
        @{ Regex = 'Claude-Session'; Label = "'Claude-Session' trailer" }
        @{ Regex = '\bGenerated with\b'; Label = "'Generated with' footer phrase" }
    )

    $failures = [System.Collections.Generic.List[string]]::new()

    # ---------------------------------------------------------------------------------------
    # 1. Tracked files.
    # ---------------------------------------------------------------------------------------
    # -I: skip files git itself detects as binary (the same heuristic `git diff` uses to print
    # "Binary files ... differ" instead of a text diff), so a .se1 ephemeris file is never opened
    # as text. -n: line numbers. --no-color, -e per pattern: one `git grep` call checks every
    # pattern in a single pass rather than one process per pattern.
    $grepArgs = @('grep', '-nI', '--no-color')
    foreach ($p in $patterns) { $grepArgs += @('-e', $p.Regex) }
    $grepArgs += @('--', '.', ':!external/*')
    # Only excludable when this script actually lives inside $RepoRoot -- e.g. a throwaway repo
    # built to exercise this script from outside its own checkout has nothing at $selfPath to
    # exclude, and a pathspec pointing outside the repo makes `git grep` refuse to run at all.
    if (-not $selfPath.StartsWith('..')) {
        $grepArgs += @(":!$selfPath")
    }

    $grepOutput = & git @grepArgs
    if ($LASTEXITCODE -eq 128) {
        throw "git grep exited 128 (not a git repository, or an invalid pathspec) -- output above."
    }
    # git grep exits 1 when nothing matched, which is the expected, good outcome here -- not an
    # error condition for this script.

    foreach ($line in @($grepOutput)) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        foreach ($p in $patterns) {
            if ($line -match $p.Regex) {
                $failures.Add("tracked file $line -- matches $($p.Label)")
                break
            }
        }
    }

    # ---------------------------------------------------------------------------------------
    # 2. Commit messages in -CommitRange.
    # ---------------------------------------------------------------------------------------
    if ($CommitRange) {
        # %H%n%B<record separator>: one record per commit (sha, then full body), split on a
        # delimiter no legitimate commit message would ever contain. `format:` (as opposed to the
        # `tformat:` that a bare `--format=STRING` with no prefix defaults to) matters here: with
        # `tformat:`, git appends its own trailing newline after every record, including the
        # last, on top of the separator this script adds. With `format:`, git still inserts
        # exactly one newline *between* records -- "separator" semantics separate, they do not
        # vanish -- but adds nothing after the final record. Either way, a record boundary in the
        # raw output is the literal separator character optionally followed by one newline
        # (present between records, absent after the last one), which is exactly what the split
        # pattern below matches; splitting on the bare separator character alone left every
        # record but the first starting with a leftover leading blank line, which made its sha
        # parse as empty and silently drop the whole record from the scan below.
        $recordSeparator = "`u{1E}"
        $raw = & git log $CommitRange "--format=format:%H%n%B$recordSeparator"
        if ($LASTEXITCODE -ne 0) {
            throw "git log $CommitRange exited $LASTEXITCODE -- is the range valid and are both ends fetched?"
        }
        $text = ($raw -join "`n")
        $recordBoundary = [regex]::Escape($recordSeparator) + '\n?'
        $records = @($text -split $recordBoundary | Where-Object { $_.Trim() -ne '' })

        foreach ($record in $records) {
            $recordLines = $record -split "`n", 2
            $sha = $recordLines[0].Trim()
            $body = if ($recordLines.Count -gt 1) { $recordLines[1] } else { '' }
            if ([string]::IsNullOrWhiteSpace($sha)) { continue }
            $shortSha = $sha.Substring(0, [Math]::Min(12, $sha.Length))

            foreach ($p in $patterns) {
                if ($body -match $p.Regex) {
                    $firstMatchLine = (@($body -split "`n") | Where-Object { $_ -match $p.Regex } | Select-Object -First 1)
                    $failures.Add("commit ${shortSha}: matches $($p.Label) -- `"$($firstMatchLine.Trim())`"")
                }
            }
        }

        Write-Host "Checked $($records.Count) commit message(s) in range $CommitRange."
    }
    else {
        Write-Host 'No -CommitRange given; commit messages were not checked.'
    }

    if ($failures.Count -gt 0) {
        Write-Host ''
        foreach ($failure in $failures) { Write-Host "  $failure" }
        Write-Host ''
        Write-Host 'FAIL: tooling-authorship text found. Remove it from the tracked file or, for a commit message, amend/reword the offending commit before merging.'
        exit 1
    }

    Write-Host 'PASS: no tooling-authorship text found in tracked files or the checked commit range.'
    exit 0
}
finally {
    Pop-Location
}
