#Requires -Version 7
<#
.SYNOPSIS
    Fails if a tracked file, or a commit message in the range under review, credits an
    automated writing tool for work in this repository.

.DESCRIPTION
    This repository's policy is that commit messages, PR text, code comments and documentation
    never say a change was produced by an automated tool -- no co-authorship trailer for one, no
    "generated with" footer, no product name in a code comment. That has been enforced by hand
    since the fork started, and by hand is not a gate: one commit message on this branch's history
    already carried a stray tool-authorship phrase before a manual scan happened to catch it.

    Four independent checks, all driven by the same pattern table and, since all now use PCRE-
    compatible regex semantics (git grep -P on one side, .NET's [regex] on the other), all give
    every pattern -- including the case-insensitive ones -- the same meaning:

      1. Every tracked file's content (git grep -a, forcing every tracked file to be scanned as
         text -- see "Binary files" below), excluding external/ (Astrodienst's own vendored
         source, not this repository's writing) and this script's own path (which necessarily
         contains the literal pattern text it searches for -- a filter has to name what it
         filters).
      1b. Every tracked file's path. `git grep` never reports a match against a path with clean
         content, so a file named e.g. ".github/copilot-instructions.md" needs a separate check
         against `git ls-files`.
      2. Every commit message in -CommitRange, if given. Skipped (not failed) when omitted, so
         this script still works as a plain content scan outside CI.
      3. Every line added anywhere in -CommitRange's diff, if given, not just what survives to
         HEAD -- a file added with a flagged phrase and deleted again later in the same range is
         invisible to checks 1 and 2 otherwise, and is still permanently in the published history.

    Pattern design, and why each one is shaped the way it is:

      - Tool and vendor product names (case-sensitive, whole-word) -- "Claude", "Anthropic",
        "ChatGPT" -- chosen case-sensitive because these are proper nouns; a false positive would
        need an unrelated identifier that happens to capitalize the same way, which nothing in a
        Swiss Ephemeris port does.
      - "assistant", "copilot", "chatbot" (case-insensitive, whole-word) -- generic terms for a
        tool that writes text on someone's behalf. Whole-word matching keeps "assistant" from
        firing on a substring of some unrelated identifier; nothing in this codebase's domain
        (ephemeris calculation) uses any of these three words for anything else, verified with
        `git grep` against the tree this script was written against.
      - "Co-Authored-By" and "Claude-Session" (case-sensitive) -- the specific trailers automated
        commit tooling appends by default.
      - "Generated with" (case-sensitive, capital G) -- the standard footer phrase
        ("Generated with [...]"), not the bare word "generated", which is ordinary and legitimate
        throughout this repository's own documentation ("the baseline is generated from the
        port's own output", "t.exp was generated by setest", "regenerated with -ExpectedScope").
        Capitalization is the deliberate discriminator: every legitimate use found in this
        repository's own text is mid-sentence and lowercase ("was generated with setest"); the
        footer this pattern exists to catch is not. A leading word boundary also keeps
        "regenerated with" from matching "Generated with" as a substring regardless of case. This
        was re-examined, not merely left alone, when the patterns below moved to PCRE: an all-caps
        "GENERATED WITH" would still slip past, and that is accepted on purpose, for the same
        reason -- widening it to (?i) would turn every legitimate lowercase "generated with" in
        this repository's own prose back into a false positive.

    Binary files: `git grep -I` (the previous flag here) skips a file two independent ways --
    git's own "does this look like text" content heuristic, AND any applicable .gitattributes
    `binary`/`-diff` entry -- and confirmed by direct testing, either one alone is enough to make
    a genuinely offending text file invisible: a tracked file saved as UTF-16LE, or UTF-8 with a
    single stray embedded NUL byte (both one click away in a Windows editor's "Save as Unicode",
    or a copy-paste artifact), trips the first; a future `.gitattributes` entry marking a path
    `binary` or `-diff` (this repository's own `.gitattributes` already ships commented-out
    template blocks for exactly that) trips the second regardless of what the file actually
    contains. `-a`/`--text` (used for both the content scan and the diff scan below) forces every
    tracked file to be processed as text regardless of either signal. The only tracked binaries in
    this repository, `Tests/SwissEphNet.Tests/files/*.se1`, were confirmed by direct testing to
    produce no match and no error under -a.

    docs/upstream/ is untracked, so `git grep` (which searches the index, not the working tree)
    never sees it regardless of any explicit exclusion.

    False positives are the one thing that gets a check like this disabled, so every pattern above
    was checked against this repository's current tree before being added, and the phrasing was
    chosen specifically to avoid the near-misses found doing that (see "Generated with" above).
    Preferring a false negative to a false positive is not merely default caution here; it is
    calibrated against defects this exact scan produced during design and then was narrowed to
    avoid.

.PARAMETER RepoRoot
    Repository root. Defaults to the checkout containing this script.

.PARAMETER CommitRange
    A git revision range (e.g. "origin/release/2.10.03..HEAD") whose commit messages are also
    checked. Typically the range a pull request actually introduces -- see the CI workflow for how
    it is resolved. Omit to check tracked files only.
#>
[CmdletBinding()]
param(
    [string] $RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [string] $CommitRange
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSNativeCommandUseErrorActionPreference = $false

Push-Location $RepoRoot
try {
    # This script's own path, relative to the repo root, in the form `git grep` reports it --
    # the one file allowed to contain the literal pattern text below.
    $selfPath = [System.IO.Path]::GetRelativePath($RepoRoot, $PSCommandPath).Replace('\', '/')

    # git grep's default regex dialect is POSIX BRE, which has no "(?i)" -- it is matched as four
    # literal characters, so every case-insensitive pattern below silently became a case-sensitive
    # one. Measured: a tracked file containing "Copilot" passed this gate at exit 0 before this
    # check existed. -P switches git grep to PCRE, which (like .NET's own regex engine used on the
    # commit-message side below) understands "(?i)" and "\b" the way every pattern here assumes.
    # Fail loudly, not with a confusing later mismatch, if this git build was not compiled with
    # PCRE support (a git grep -P call always exits non-zero without it). Probes against pathspec
    # "." (the whole of $RepoRoot, already the current location) rather than $selfPath, which may
    # sit outside $RepoRoot -- see the "throwaway repo" comment below -- and would make git grep
    # refuse with exit 128 for a reason that has nothing to do with PCRE support. A match is not
    # required (an empty repo legitimately exits 1, "no match"); only "git refused to run this
    # regex dialect at all" (anything past 1) means PCRE is unavailable.
    $null = & git grep -P -q '(?i)^' -- . 2>&1
    if ($LASTEXITCODE -gt 1) {
        throw "git grep -P (PCRE) is required by this script's pattern table but this git build does not support it (exit $LASTEXITCODE). Install a git built with PCRE2 support."
    }

    # Each pattern paired with a human-readable label for the failure message. Patterns are PCRE
    # (git grep -P) on the tracked-file side and .NET regex (see part 2 below) on the
    # commit-message side -- the same syntax for everything used here, so one pattern table serves
    # both. A leading "(?i)" makes that one pattern case-insensitive, its absence means
    # case-sensitive -- see the .DESCRIPTION for why each choice was made.
    $patterns = @(
        @{ Regex = '\bClaude\b'; Label = "product name 'Claude'" }
        @{ Regex = '\bAnthropic\b'; Label = "company name 'Anthropic'" }
        @{ Regex = '\bChatGPT\b'; Label = "product name 'ChatGPT'" }
        @{ Regex = '(?i)\bcopilot\b'; Label = "'copilot'" }
        @{ Regex = '(?i)\bchatbot\b'; Label = "'chatbot'" }
        @{ Regex = '(?i)\bassistant\b'; Label = "'assistant'" }
        @{ Regex = 'Co-Authored-By'; Label = "'Co-Authored-By' trailer" }
        @{ Regex = 'Claude-Session'; Label = "'Claude-Session' trailer" }
        @{ Regex = '\bGenerated with\b'; Label = "'Generated with' footer phrase" }
    )

    $failures = [System.Collections.Generic.List[string]]::new()

    # ---------------------------------------------------------------------------------------
    # 1. Tracked files' content.
    # ---------------------------------------------------------------------------------------
    # -a ("--text"), not -I: -I skips both (a) any file git's own "does this look like text"
    # heuristic calls binary, AND (b) any file an applicable .gitattributes entry marks `binary`
    # or `-diff` -- confirmed by direct testing, both independently make a real text file
    # invisible to -I regardless of what it actually contains. A tracked file saved as UTF-16LE,
    # or plain UTF-8 with one stray embedded NUL byte (either one is one click away in a Windows
    # editor's "Save as Unicode", or a copy-paste from a source that had one), trips git's
    # heuristic; this repository's own .gitattributes already ships commented-out `binary`/`-diff`
    # template blocks, so a future entry doing that deliberately is also one edit away. -a forces
    # every tracked file to be scanned as text regardless of either signal, closing both at once;
    # the only tracked binaries in this repository (Tests/SwissEphNet.Tests/files/*.se1) were
    # confirmed by direct testing to produce no match and no error under -a.
    # -n: line numbers. -P: PCRE, so "(?i)" and "\b" mean what the pattern table above assumes
    # instead of being matched as literal text under the default POSIX BRE dialect. --no-color,
    # -e per pattern: one `git grep` call checks every pattern in a single pass rather than one
    # process per pattern.
    $grepArgs = @('grep', '-nPa', '--no-color')
    foreach ($p in $patterns) { $grepArgs += @('-e', $p.Regex) }
    $grepArgs += @('--', '.', ':!external/*')
    # Only excludable when this script actually lives inside $RepoRoot -- e.g. a throwaway repo
    # built to exercise this script from outside its own checkout has nothing at $selfPath to
    # exclude, and a pathspec pointing outside the repo makes `git grep` refuse to run at all.
    if (-not $selfPath.StartsWith('..')) {
        $grepArgs += @(":!$selfPath")
    }

    $grepOutput = & git @grepArgs
    if ($LASTEXITCODE -eq 128) {
        throw "git grep exited 128 (not a git repository, or an invalid pathspec) -- output above."
    }
    # git grep exits 1 when nothing matched, which is the expected, good outcome here -- not an
    # error condition for this script.

    foreach ($line in @($grepOutput)) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        foreach ($p in $patterns) {
            # [regex]::IsMatch, not PowerShell's -match operator: -match is case-insensitive by
            # default regardless of what the pattern string itself says, which silently defeated
            # every pattern above that omits an explicit "(?i)" and relies on being
            # case-sensitive (Claude, Anthropic, ChatGPT, Co-Authored-By, Claude-Session, and
            # critically "Generated with", whose whole point is to NOT match the lowercase
            # "generated with" this repository's own prose legitimately uses). [regex]::IsMatch
            # honors each pattern's own case-sensitivity exactly as written.
            if ([regex]::IsMatch($line, $p.Regex)) {
                $failures.Add("tracked file $line -- matches $($p.Label)")
                break
            }
        }
    }

    # ---------------------------------------------------------------------------------------
    # 1b. Tracked files' paths themselves.
    # ---------------------------------------------------------------------------------------
    # `git grep` only ever emits a line for a match inside a file's *content* -- it has no mode
    # that reports a match against the path alone, so a file named e.g.
    # ".github/copilot-instructions.md" with entirely clean content never produces a line for the
    # loop above to see, no matter how the patterns are written. That is a conventional filename
    # (GitHub's own suggested name for repo-level Copilot instructions) that can land without
    # anyone intending an attribution violation. `git ls-files` lists every tracked path
    # regardless of content, so it is checked against the same pattern table separately.
    $trackedPaths = & git ls-files -- '.' ':!external/*'
    if ($LASTEXITCODE -ne 0) {
        throw "git ls-files exited $LASTEXITCODE -- output above."
    }
    foreach ($path in @($trackedPaths)) {
        if ([string]::IsNullOrWhiteSpace($path)) { continue }
        if (-not $selfPath.StartsWith('..') -and $path -eq $selfPath) { continue }
        foreach ($p in $patterns) {
            if ([regex]::IsMatch($path, $p.Regex)) {
                $failures.Add("tracked path '$path' -- matches $($p.Label)")
                break
            }
        }
    }

    # ---------------------------------------------------------------------------------------
    # 2. Commit messages in -CommitRange.
    # ---------------------------------------------------------------------------------------
    if ($CommitRange) {
        # %H%n%B<record separator>: one record per commit (sha, then full body), split on a
        # delimiter no legitimate commit message would ever contain. `format:` (as opposed to the
        # `tformat:` that a bare `--format=STRING` with no prefix defaults to) matters here: with
        # `tformat:`, git appends its own trailing newline after every record, including the
        # last, on top of the separator this script adds. With `format:`, git still inserts
        # exactly one newline *between* records -- "separator" semantics separate, they do not
        # vanish -- but adds nothing after the final record. Either way, a record boundary in the
        # raw output is the literal separator character optionally followed by one newline
        # (present between records, absent after the last one), which is exactly what the split
        # pattern below matches; splitting on the bare separator character alone left every
        # record but the first starting with a leftover leading blank line, which made its sha
        # parse as empty and silently drop the whole record from the scan below.
        $recordSeparator = "`u{1E}"
        $raw = & git log $CommitRange "--format=format:%H%n%B$recordSeparator"
        if ($LASTEXITCODE -ne 0) {
            throw "git log $CommitRange exited $LASTEXITCODE -- is the range valid and are both ends fetched?"
        }
        $text = ($raw -join "`n")
        $recordBoundary = [regex]::Escape($recordSeparator) + '\n?'
        $records = @($text -split $recordBoundary | Where-Object { $_.Trim() -ne '' })

        foreach ($record in $records) {
            $recordLines = $record -split "`n", 2
            $sha = $recordLines[0].Trim()
            $body = if ($recordLines.Count -gt 1) { $recordLines[1] } else { '' }
            if ([string]::IsNullOrWhiteSpace($sha)) { continue }
            $shortSha = $sha.Substring(0, [Math]::Min(12, $sha.Length))

            foreach ($p in $patterns) {
                # [regex]::IsMatch here too -- see the identical comment on the tracked-file loop
                # above for why -match's default case-insensitivity is unsafe for this table.
                if ([regex]::IsMatch($body, $p.Regex)) {
                    $firstMatchLine = (@($body -split "`n") | Where-Object { [regex]::IsMatch($_, $p.Regex) } | Select-Object -First 1)
                    $failures.Add("commit ${shortSha}: matches $($p.Label) -- `"$($firstMatchLine.Trim())`"")
                }
            }
        }

        Write-Host "Checked $($records.Count) commit message(s) in range $CommitRange."

        # -----------------------------------------------------------------------------------
        # 3. Lines added anywhere in -CommitRange's diff, not just what survives to HEAD.
        # -----------------------------------------------------------------------------------
        # Check 1 above only ever reads HEAD's own tracked content. A file added with a flagged
        # phrase in one commit and deleted again in a later commit, both inside the same range
        # (drafting and then removing a doc inside one PR/push is ordinary), is invisible to that
        # check -- it was never in HEAD -- and invisible to check 2 as well, since a file's own
        # content is not a commit message. The phrase still permanently exists in the published
        # history, which is exactly what this script exists to prevent. `git log -p` walks every
        # commit's own diff, so a line added in commit A of the range is seen when A is visited,
        # independent of what any later commit in the same range does to it.
        #
        # A per-commit marker (the same record-separator technique as the message scan above)
        # attributes each added line to the commit that introduced it. Only lines that are pure
        # additions (a single leading '+', not the "+++ b/path" file-header line diff emits for
        # every file) are scanned -- context lines and removals are not new content this range
        # introduced. -a ("--text"): the same reasoning as check 1's -a applies to diff output
        # too -- without it, a blob git's heuristic calls binary renders as "Binary files ...
        # differ" with no +/- lines at all, silently skipping a NUL-byte-disguised addition.
        $diffRecordSeparator = "`u{1E}"
        $diffGrepArgs = @(
            'log', $CommitRange, '-p', '-a', '--no-color',
            "--format=format:$diffRecordSeparator%H",
            '--', '.', ':!external/*')
        if (-not $selfPath.StartsWith('..')) { $diffGrepArgs += ":!$selfPath" }
        $diffRaw = & git @diffGrepArgs
        if ($LASTEXITCODE -ne 0) {
            throw "git log $CommitRange -p exited $LASTEXITCODE -- is the range valid and are both ends fetched?"
        }
        $diffText = ($diffRaw -join "`n")
        $diffRecordBoundary = [regex]::Escape($diffRecordSeparator)
        $diffRecords = @($diffText -split $diffRecordBoundary | Where-Object { $_.Trim() -ne '' })

        foreach ($record in $diffRecords) {
            $recordLines = $record -split "`n", 2
            $sha = $recordLines[0].Trim()
            $diffBody = if ($recordLines.Count -gt 1) { $recordLines[1] } else { '' }
            if ([string]::IsNullOrWhiteSpace($sha)) { continue }
            $shortSha = $sha.Substring(0, [Math]::Min(12, $sha.Length))

            foreach ($diffLine in @($diffBody -split "`n")) {
                if (-not $diffLine.StartsWith('+') -or $diffLine.StartsWith('+++')) { continue }
                $added = $diffLine.Substring(1)
                foreach ($p in $patterns) {
                    if ([regex]::IsMatch($added, $p.Regex)) {
                        $failures.Add("commit ${shortSha} added a line matching $($p.Label) -- `"$($added.Trim())`" (even if a later commit in the same range removed it, it is permanently in the published history)")
                        break
                    }
                }
            }
        }
    }
    else {
        Write-Host 'No -CommitRange given; commit messages were not checked.'
    }

    if ($failures.Count -gt 0) {
        Write-Host ''
        foreach ($failure in $failures) { Write-Host "  $failure" }
        Write-Host ''
        Write-Host 'FAIL: tooling-authorship text found. Remove it from the tracked file or, for a commit message, amend/reword the offending commit before merging.'
        exit 1
    }

    Write-Host 'PASS: no tooling-authorship text found in tracked files or the checked commit range.'
    exit 0
}
finally {
    Pop-Location
}
