<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SweWin</RootNamespace>
    <AssemblyName>SweWin</AssemblyName>
    <Product>SweWin</Product>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SwissEphNet\SwissEphNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Datas\sedeltat.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
